# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rKvg1L98JlJuetoHePztwDuTA-WmwbQY
"""

import pandas as pd
from bokeh.io import output_file, output_notebook, show
from bokeh.plotting import figure, ColumnDataSource
output_notebook()
from bokeh.io import curdoc
from bokeh.plotting import figure
from bokeh.models import HoverTool, ColumnDataSource, DatePicker
from bokeh.models import CategoricalColorMapper
from bokeh.palettes import Spectral6

data_vis = pd.read_csv('./data_visdat.csv')

Chi_Source = data_vis.loc[:, ['Latitude', 'Longitude']]
Chi_Source.drop(Chi_Source.columns[0], axis=1,inplace=True)

L_Source = ColumnDataSource(data=dict(x=data_vis['Latitude'],
                                      y=data_vis['Longitude'],
                                      province=data_vis['Province'].values,
                                      island=data_vis['Island'].values))
TOOLS = "pan,wheel_zoom,box_zoom,reset,hover,save" 
Elevated = figure(title="Covid-19", 
                tools=TOOLS,
                x_axis_location=None, 
                y_axis_location=None)
Elevated.multi_line('x', 
                    'y', 
                    source=Chi_Source, 
                    color="black", 
                    line_width=2) 
Elevated.circle('x', 
                'y', 
                source=L_Source, 
                size=4)
hover = Elevated.select_one(HoverTool)
hover.point_policy = "follow_mouse"
hover.tooltips = [
        ("Province", "@Province"),
        ("Island", "@Island"),
        ("(Long, Lat)", "($x, $y)"),
        ]
show(Elevated)
